### PR TITLE
Remove SessionController

### PR DESCRIPTION
**Pull request by stephanheilner**

### CODE REVIEW

**Comment by hiltonc** [comment]
It doesn't look like this removes SessionController?

**Comment by stephanheilner** [comment]
Its there: https://github.com/CrossWaterBridge/LDSAnnotations/pull/57/files#diff-2ae62f207f85b2976c24112e3cbf3008

**Comment by hiltonc** [comment]
Ahhhh, tricky.

**Comment by stephanheilner** [comment]
Tests pass locally, fwiw.

**Pull request merged**
