### PR TITLE
Test and fix annotation notifications; improvements to demo

### PR DESCRIPTION
**Pull request by hiltonc**
Demo improvements:

* Refresh account screen when annotations change
* Order annotations by last modified
* Show annotation types in annotations screen
* Sync when annotations change

### CODE REVIEW

**Comment by stephanheilner** [comment]
👍  Looks great!

**Comment by hiltonc** [comment]
Force pushed a rebase.

**Comment by nickmshelley** [comment]
@hiltonc You know with squash and merge that extra merge commits don't really matter any more, right? Just sayin'...

**Comment by hiltonc** [comment]
Old habits are hard to break :)

**Pull request merged**
