### PR TITLE
Fixed missing table column

### PR DESCRIPTION
**Pull request by brandenr**
Fixed using incorrect table
Bump version

### CODE REVIEW

**Comment by hiltonc** [comment]
Can you add a quick little test for this? I think you can base it on `testAddNote` in https://github.com/CrossWaterBridge/LDSAnnotations/blob/master/LDSAnnotationsTests/AnnotationStoreTests.swift

**Comment by hiltonc** [comment]
Also, for Travis CI to run tests you'll need to push your PR branch to this repo instead of your fork. This is because the tests use encrypted data, which Travis CI disables when building from forks. We can skip that for this, but it's something we can all do in the future.

**Comment by nickmshelley** [comment]
Doesn't that mean that only committers can make PRs where all the tests will run? Or does it not matter since everyone that contributes is a committer anyway?

**Comment by brandenr** [comment]
https://github.com/CrossWaterBridge/LDSAnnotations/pull/11

**Comment by hiltonc** [comment]
@nickmshelley Yes, and yes.

**Pull request closed without merging**
