### PR TITLE
Add string description to error logger.

### PR DESCRIPTION
**Pull request by nickmshelley**

### CODE REVIEW

**Comment by hiltonc** [comment]
Maybe not useful in all cases, but `#function` might be a useful macro for this.

**Comment by stephanheilner** [comment]
I was trying to make the same comment! I think using #function is a better approach.

**Comment by stephanheilner** [comment]
Just add a function like this:
```
static func logError(function: String = #function, line: Int = #line, error: Error) {
        let message = "\(function) (\(line))"
        logErrorHandler?(message, error)
    }
```
And use that instead of the static var.

**Comment by nickmshelley** [comment]
Well, I wish I had talked to someone before wasting so much time on those stupid strings... 😅

**Pull request closed without merging**
